[theme]
primaryColor              = "#4361EE"
backgroundColor           = "#0A1628"
secondaryBackgroundColor  = "#0F2044"
textColor                 = "#F8F9FC"
font                      = "sans serif"

[server]
maxUploadSize             = 15
enableCORS                = false
enableXsrfProtection      = true

[runner]
fastReruns                = true

[client]
showErrorDetails          = false
toolbarMode               = "minimal"
