"""
exporter.py — Generate downloadable PDF and DOCX from the literature review.
"""

import io
import re
from datetime import datetime


def generate_pdf(review_text: str, references_text: str,
                 topic: str, citation_style: str) -> bytes:
    """Generate a formatted academic PDF using ReportLab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch, cm
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                    HRFlowable, PageBreak)
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY

    INDIGO = colors.HexColor("#4361EE")
    NAVY   = colors.HexColor("#0A1628")
    TEAL   = colors.HexColor("#06D6A0")
    DARK   = colors.HexColor("#1A2A40")
    MUTED  = colors.HexColor("#6B7A99")
    BLACK  = colors.HexColor("#1a1a2e")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=2.2*cm, bottomMargin=2.2*cm,
        leftMargin=2.5*cm, rightMargin=2.5*cm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("Title", fontSize=20, fontName="Helvetica-Bold",
                                  textColor=NAVY, alignment=TA_CENTER,
                                  spaceAfter=6, leading=26)
    meta_style  = ParagraphStyle("Meta", fontSize=9, fontName="Helvetica",
                                  textColor=MUTED, alignment=TA_CENTER, spaceAfter=18)
    h1_style    = ParagraphStyle("H1", fontSize=13, fontName="Helvetica-Bold",
                                  textColor=INDIGO, spaceBefore=18, spaceAfter=6, leading=18)
    body_style  = ParagraphStyle("Body", fontSize=11, fontName="Times-Roman",
                                  textColor=BLACK, alignment=TA_JUSTIFY,
                                  spaceAfter=10, leading=17)
    ref_title   = ParagraphStyle("RefTitle", fontSize=12, fontName="Helvetica-Bold",
                                  textColor=NAVY, spaceBefore=20, spaceAfter=8)
    ref_style   = ParagraphStyle("Ref", fontSize=10, fontName="Helvetica",
                                  textColor=DARK, spaceAfter=6, leading=14, leftIndent=18,
                                  firstLineIndent=-18)
    footer_style= ParagraphStyle("Footer", fontSize=8, fontName="Helvetica",
                                  textColor=MUTED, alignment=TA_CENTER)

    story = []

    # ── Header bar ────────────────────────────────────────────────
    story.append(Paragraph("ScholarAI — Literature Review", meta_style))
    story.append(HRFlowable(width="100%", thickness=2, color=INDIGO, spaceAfter=12))

    # ── Title ─────────────────────────────────────────────────────
    story.append(Paragraph(_rl_escape(topic), title_style))
    date_str = datetime.now().strftime("%B %d, %Y")
    meta_line = f"Literature Review  ·  {citation_style}  ·  Generated {date_str}"
    story.append(Paragraph(_rl_escape(meta_line), meta_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#D5DCF0"),
                             spaceAfter=16))

    # ── Review body ───────────────────────────────────────────────
    paragraphs = review_text.split("\n")
    for para in paragraphs:
        para = para.strip()
        if not para:
            story.append(Spacer(1, 6))
            continue
        if para.startswith("## "):
            heading = para[3:].strip()
            story.append(Spacer(1, 8))
            story.append(Paragraph(_rl_escape(heading), h1_style))
            story.append(HRFlowable(width="40%", thickness=1, color=TEAL, spaceAfter=6))
        elif para.startswith("# "):
            heading = para[2:].strip()
            story.append(Spacer(1, 10))
            story.append(Paragraph(_rl_escape(heading), h1_style))
        else:
            # Escape special chars for ReportLab
            safe = _rl_escape(para)
            story.append(Paragraph(safe, body_style))

    # ── References ────────────────────────────────────────────────
    story.append(Spacer(1, 18))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=colors.HexColor("#D5DCF0"), spaceAfter=10))
    story.append(Paragraph("References", ref_title))
    for ref in references_text.split("\n\n"):
        ref = ref.strip()
        if ref:
            story.append(Paragraph(_rl_escape(ref), ref_style))

    # ── Disclaimer ────────────────────────────────────────────────
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.HexColor("#D5DCF0"), spaceAfter=6))
    story.append(Paragraph(
        "Generated by ScholarAI · AI-assisted draft — review and verify before submission · "
        "scholarai.streamlit.app",
        footer_style
    ))

    doc.build(story)
    return buf.getvalue()


def generate_docx(review_text: str, references_text: str,
                  topic: str, citation_style: str) -> bytes:
    """Generate a formatted DOCX using python-docx."""
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    INDIGO = RGBColor(0x43, 0x61, 0xEE)
    NAVY   = RGBColor(0x0A, 0x16, 0x28)
    TEAL   = RGBColor(0x06, 0xD6, 0xA0)
    DARK   = RGBColor(0x1A, 0x2A, 0x40)
    MUTED  = RGBColor(0x6B, 0x7A, 0x99)

    doc = Document()
    # Page margins
    for section in doc.sections:
        section.top_margin    = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin   = Cm(3.0)
        section.right_margin  = Cm(3.0)

    def set_run_font(run, size=11, bold=False, italic=False, color=DARK):
        run.font.name  = "Times New Roman" if not bold else "Arial"
        run.font.size  = Pt(size)
        run.font.bold  = bold
        run.font.italic= italic
        run.font.color.rgb = color

    # ── Title ─────────────────────────────────────────────────────
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = title_p.add_run(topic)
    set_run_font(r, size=18, bold=True, color=NAVY)

    sub_p = doc.add_paragraph()
    sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_str = datetime.now().strftime("%B %d, %Y")
    r = sub_p.add_run(f"Literature Review  ·  {citation_style}  ·  Generated {date_str}")
    set_run_font(r, size=9, color=MUTED)
    sub_p.paragraph_format.space_after = Pt(16)

    # Divider via border
    _add_paragraph_border(sub_p)

    # ── Review body ───────────────────────────────────────────────
    for line in review_text.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("## "):
            heading = line[3:].strip()
            hp = doc.add_heading(heading, level=2)
            for run in hp.runs:
                run.font.color.rgb = INDIGO
                run.font.name = "Arial"
        elif line.startswith("# "):
            heading = line[2:].strip()
            hp = doc.add_heading(heading, level=1)
            for run in hp.runs:
                run.font.color.rgb = NAVY
        else:
            bp = doc.add_paragraph()
            bp.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            bp.paragraph_format.space_after = Pt(8)
            bp.paragraph_format.line_spacing = Pt(18)
            r = bp.add_run(line)
            set_run_font(r, size=11, color=DARK)

    # ── References ────────────────────────────────────────────────
    doc.add_paragraph()
    rh = doc.add_heading("References", level=1)
    for run in rh.runs:
        run.font.color.rgb = NAVY
    _add_paragraph_border(rh)

    for ref in references_text.split("\n\n"):
        ref = ref.strip()
        if ref:
            rp = doc.add_paragraph()
            rp.paragraph_format.left_indent  = Cm(1)
            rp.paragraph_format.first_line_indent = Cm(-1)
            rp.paragraph_format.space_after  = Pt(6)
            r = rp.add_run(ref)
            set_run_font(r, size=10, color=DARK)

    # ── Disclaimer ────────────────────────────────────────────────
    dp = doc.add_paragraph()
    dp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    dp.paragraph_format.space_before = Pt(20)
    r = dp.add_run(
        "Generated by ScholarAI · AI-assisted draft — review and verify before submission"
    )
    set_run_font(r, size=8, italic=True, color=MUTED)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _add_paragraph_border(para):
    """Add a bottom border to a paragraph via XML."""
    try:
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        pPr = para._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"), "single")
        bottom.set(qn("w:sz"), "6")
        bottom.set(qn("w:space"), "4")
        bottom.set(qn("w:color"), "4361EE")
        pBdr.append(bottom)
        pPr.append(pBdr)
    except Exception:
        pass


def _rl_escape(text: str) -> str:
    """Escape special XML characters for ReportLab Paragraph."""
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    return text
